using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SanatorioHMS.Domain.Auth.Entities;
using SanatorioHMS.Domain.ClinicalCare.Entities;
using SanatorioHMS.Domain.Diagnostics.Entities;
using SanatorioHMS.Domain.PatientRegistry.Entities;
using SanatorioHMS.Domain.Scheduling.Entities;

namespace SanatorioHMS.Infrastructure.Data;

public sealed class PatientConfiguration : IEntityTypeConfiguration<Patient> { public void Configure(EntityTypeBuilder<Patient> b) { b.ToTable("Patients"); b.HasKey(x => x.Id); b.Property(x => x.Name).HasMaxLength(100).IsRequired(); b.Property(x => x.Surname).HasMaxLength(100).IsRequired(); } }
public sealed class PatientDocumentConfiguration : IEntityTypeConfiguration<PatientDocument> { public void Configure(EntityTypeBuilder<PatientDocument> b) { b.ToTable("PatientDocuments"); b.HasKey(x => x.Id); b.HasIndex(x => new { x.DocumentType, x.DocumentNumber }).IsUnique(); b.Property(x => x.DocumentNumber).HasMaxLength(50).IsRequired(); b.HasOne(x => x.Patient).WithMany(x => x.Documents).HasForeignKey(x => x.PatientId).OnDelete(DeleteBehavior.Restrict); } }
public sealed class PatientContactConfiguration : IEntityTypeConfiguration<PatientContact> { public void Configure(EntityTypeBuilder<PatientContact> b) { b.ToTable("PatientContacts"); b.HasKey(x => x.Id); b.HasOne(x => x.Patient).WithMany(x => x.Contacts).HasForeignKey(x => x.PatientId).OnDelete(DeleteBehavior.Cascade); } }
public sealed class HealthCoverageConfiguration : IEntityTypeConfiguration<HealthCoverage> { public void Configure(EntityTypeBuilder<HealthCoverage> b) { b.ToTable("HealthCoverages"); b.HasKey(x => x.Id); b.HasOne(x => x.Patient).WithMany(x => x.Coverages).HasForeignKey(x => x.PatientId).OnDelete(DeleteBehavior.Restrict); } }
public sealed class GuardianConfiguration : IEntityTypeConfiguration<GuardianRelationship> { public void Configure(EntityTypeBuilder<GuardianRelationship> b) { b.ToTable("GuardianRelationships"); b.HasKey(x => x.Id); b.HasOne(x => x.Patient).WithMany(x => x.Guardians).HasForeignKey(x => x.PatientId).OnDelete(DeleteBehavior.Restrict); } }

public sealed class SchedulingConfiguration : IEntityTypeConfiguration<Turno> { public void Configure(EntityTypeBuilder<Turno> b) { b.ToTable("Turns"); b.HasKey(x => x.Id); b.HasIndex(x => new { x.AgendaId, x.FechaHora }).IsUnique(); b.Property<byte[]>("RowVersion").IsRowVersion(); b.HasOne(x => x.Agenda).WithMany(x => x.Turnos).HasForeignKey(x => x.AgendaId).OnDelete(DeleteBehavior.Restrict); } }
public sealed class AgendaConfiguration : IEntityTypeConfiguration<Agenda> { public void Configure(EntityTypeBuilder<Agenda> b) { b.ToTable("Agendas"); b.HasKey(x => x.Id); b.HasOne(x => x.Profesional).WithMany(x => x.Agendas).HasForeignKey(x => x.ProfesionalId).OnDelete(DeleteBehavior.Restrict); b.HasOne(x => x.Especialidad).WithMany().HasForeignKey(x => x.EspecialidadId).OnDelete(DeleteBehavior.Restrict); } }
public sealed class ProfessionalConfiguration : IEntityTypeConfiguration<Professional> { public void Configure(EntityTypeBuilder<Professional> b) { b.ToTable("Professionals"); b.HasKey(x => x.Id); } }
public sealed class SpecialtyConfiguration : IEntityTypeConfiguration<Specialty> { public void Configure(EntityTypeBuilder<Specialty> b) { b.ToTable("Specialties"); b.HasKey(x => x.Id); } }
public sealed class ProfessionalSpecialtyConfiguration : IEntityTypeConfiguration<ProfessionalSpecialty> { public void Configure(EntityTypeBuilder<ProfessionalSpecialty> b) { b.ToTable("ProfessionalSpecialties"); b.HasKey(x => new { x.ProfessionalId, x.SpecialtyId }); b.HasOne(x => x.Professional).WithMany(x => x.ProfessionalSpecialties).HasForeignKey(x => x.ProfessionalId).OnDelete(DeleteBehavior.Restrict); b.HasOne(x => x.Specialty).WithMany(x => x.Professionals).HasForeignKey(x => x.SpecialtyId).OnDelete(DeleteBehavior.Restrict); } }
public sealed class RoomConfiguration : IEntityTypeConfiguration<Room> { public void Configure(EntityTypeBuilder<Room> b) { b.ToTable("Rooms"); b.HasKey(x => x.Id); } }

public sealed class EpisodeConfiguration : IEntityTypeConfiguration<Episode> { public void Configure(EntityTypeBuilder<Episode> b) { b.ToTable("Episodes"); b.HasKey(x => x.Id); } }
public sealed class EncounterConfiguration : IEntityTypeConfiguration<Encounter> { public void Configure(EntityTypeBuilder<Encounter> b) { b.ToTable("Encounters"); b.HasKey(x => x.Id); b.HasOne(x => x.Episode).WithMany(x => x.Encounters).HasForeignKey(x => x.EpisodioId).OnDelete(DeleteBehavior.Restrict); } }
public sealed class ClinicalNoteConfiguration : IEntityTypeConfiguration<ClinicalNote> { public void Configure(EntityTypeBuilder<ClinicalNote> b) { b.ToTable("ClinicalNotes"); b.HasKey(x => x.Id); b.HasOne(x => x.Episode).WithMany(x => x.ClinicalNotes).HasForeignKey(x => x.EpisodioId).OnDelete(DeleteBehavior.Restrict); } }
public sealed class OrderConfiguration : IEntityTypeConfiguration<Order> { public void Configure(EntityTypeBuilder<Order> b) { b.ToTable("Orders"); b.HasKey(x => x.Id); b.HasOne(x => x.Episode).WithMany(x => x.Orders).HasForeignKey(x => x.EpisodioId).OnDelete(DeleteBehavior.Restrict); b.HasOne(x => x.Encounter).WithMany(x => x.Orders).HasForeignKey(x => x.AtencionId).OnDelete(DeleteBehavior.Restrict); } }
public sealed class OrderItemConfiguration : IEntityTypeConfiguration<OrderItem> { public void Configure(EntityTypeBuilder<OrderItem> b) { b.ToTable("OrderItems"); b.HasKey(x => x.Id); b.HasOne(x => x.Order).WithMany(x => x.Items).HasForeignKey(x => x.OrdenId).OnDelete(DeleteBehavior.Restrict); } }

public sealed class StudyConfiguration : IEntityTypeConfiguration<Study> { public void Configure(EntityTypeBuilder<Study> b) { b.ToTable("Studies"); b.HasKey(x => x.Id); b.HasIndex(x => new { x.Code, x.Version }).IsUnique(); } }
public sealed class DiagnosticOrderConfiguration : IEntityTypeConfiguration<DiagnosticOrder> { public void Configure(EntityTypeBuilder<DiagnosticOrder> b) { b.ToTable("DiagnosticOrders"); b.HasKey(x => x.Id); b.HasIndex(x => new { x.PatientId, x.Authorization }); } }
public sealed class DiagnosticResultConfiguration : IEntityTypeConfiguration<DiagnosticResult> { public void Configure(EntityTypeBuilder<DiagnosticResult> b) { b.ToTable("DiagnosticResults"); b.HasKey(x => x.Id); b.HasOne<DiagnosticOrder>().WithMany().HasForeignKey(x => x.DiagnosticOrderId).OnDelete(DeleteBehavior.Restrict); } }

public sealed class UserConfiguration : IEntityTypeConfiguration<User> { public void Configure(EntityTypeBuilder<User> b) { b.ToTable("Users"); b.HasKey(x => x.Id); b.HasIndex(x => x.Username).IsUnique(); b.Property(x => x.PasswordHash).HasMaxLength(500).IsRequired(); } }
public sealed class RoleConfiguration : IEntityTypeConfiguration<Role> { public void Configure(EntityTypeBuilder<Role> b) { b.ToTable("Roles"); b.HasKey(x => x.Id); b.HasIndex(x => x.Name).IsUnique(); } }
public sealed class PermissionConfiguration : IEntityTypeConfiguration<Permission> { public void Configure(EntityTypeBuilder<Permission> b) { b.ToTable("Permissions"); b.HasKey(x => x.Id); b.HasIndex(x => x.Code).IsUnique(); } }
public sealed class SessionConfiguration : IEntityTypeConfiguration<Session> { public void Configure(EntityTypeBuilder<Session> b) { b.ToTable("Sessions"); b.HasKey(x => x.Id); b.Property(x => x.RefreshTokenHash).HasMaxLength(128); b.HasOne<User>().WithMany(x => x.Sessions).HasForeignKey(x => x.UserId).OnDelete(DeleteBehavior.Restrict); } }
public sealed class AuditLogConfiguration : IEntityTypeConfiguration<AuditLog> { public void Configure(EntityTypeBuilder<AuditLog> b) { b.ToTable("AuditLogs"); b.HasKey(x => x.Id); b.Property(x => x.Action).HasMaxLength(200).IsRequired(); b.Property(x => x.Target).HasMaxLength(300).IsRequired(); b.Property(x => x.Outcome).HasMaxLength(100).IsRequired(); b.Property(x => x.PreviousHash).HasMaxLength(128); b.Property(x => x.Hash).HasMaxLength(128).IsRequired(); b.HasIndex(x => x.RecordedAt); b.HasOne<User>().WithMany().HasForeignKey(x => x.ActorId).OnDelete(DeleteBehavior.Restrict); } }
