// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SanatorioHMS.Infrastructure.Data;

#nullable disable

namespace SanatorioHMS.Infrastructure.Data.Migrations.ClinicalCareDb
{
    [DbContext(typeof(ClinicalCareDbContext))]
    partial class ClinicalCareDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("clinical")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SanatorioHMS.Domain.ClinicalCare.Entities.ClinicalNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AtencionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EpisodioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EsPrivada")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ProfesionalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TipoNota")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EpisodioId");

                    b.ToTable("ClinicalNotes", "clinical");
                });

            modelBuilder.Entity("SanatorioHMS.Domain.ClinicalCare.Entities.Encounter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Anamnesis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Diagnosticos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EpisodioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExamenFisico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("Motivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlanTrabajo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProfesionalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EpisodioId");

                    b.ToTable("Encounters", "clinical");
                });

            modelBuilder.Entity("SanatorioHMS.Domain.ClinicalCare.Entities.Episode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Anamnesis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiagnosticoPrincipal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiagnosticoPrincipalCIE10")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExamenFisico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEgreso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<string>("MotivoIngreso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PlanTerapeutico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProfesionalIngresoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ViaIngreso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Episodes", "clinical");
                });

            modelBuilder.Entity("SanatorioHMS.Domain.ClinicalCare.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AtencionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EpisodioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaCumplimiento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaOrden")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ProfesionalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AtencionId");

                    b.HasIndex("EpisodioId");

                    b.ToTable("Orders", "clinical");
                });

            modelBuilder.Entity("SanatorioHMS.Domain.ClinicalCare.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dosis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Duracion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Frecuencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrdenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ViaAdministracion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrdenId");

                    b.ToTable("OrderItems", "clinical");
                });

            modelBuilder.Entity("SanatorioHMS.Domain.ClinicalCare.Entities.ClinicalNote", b =>
                {
                    b.HasOne("SanatorioHMS.Domain.ClinicalCare.Entities.Episode", "Episode")
                        .WithMany("ClinicalNotes")
                        .HasForeignKey("EpisodioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Episode");
                });

            modelBuilder.Entity("SanatorioHMS.Domain.ClinicalCare.Entities.Encounter", b =>
                {
                    b.HasOne("SanatorioHMS.Domain.ClinicalCare.Entities.Episode", "Episode")
                        .WithMany("Encounters")
                        .HasForeignKey("EpisodioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Episode");
                });

            modelBuilder.Entity("SanatorioHMS.Domain.ClinicalCare.Entities.Order", b =>
                {
                    b.HasOne("SanatorioHMS.Domain.ClinicalCare.Entities.Encounter", "Encounter")
                        .WithMany("Orders")
                        .HasForeignKey("AtencionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SanatorioHMS.Domain.ClinicalCare.Entities.Episode", "Episode")
                        .WithMany("Orders")
                        .HasForeignKey("EpisodioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Encounter");

                    b.Navigation("Episode");
                });

            modelBuilder.Entity("SanatorioHMS.Domain.ClinicalCare.Entities.OrderItem", b =>
                {
                    b.HasOne("SanatorioHMS.Domain.ClinicalCare.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrdenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("SanatorioHMS.Domain.ClinicalCare.Entities.Encounter", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("SanatorioHMS.Domain.ClinicalCare.Entities.Episode", b =>
                {
                    b.Navigation("ClinicalNotes");

                    b.Navigation("Encounters");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("SanatorioHMS.Domain.ClinicalCare.Entities.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
