<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\Application\SanatorioHMS.Application.Core\SanatorioHMS.Application.Core.csproj" />
    <ProjectReference Include="..\..\Application\SanatorioHMS.Application.Auth\SanatorioHMS.Application.Auth.csproj" />
    <ProjectReference Include="..\..\Application\SanatorioHMS.Application.PatientRegistry\SanatorioHMS.Application.PatientRegistry.csproj" />
    <ProjectReference Include="..\..\Application\SanatorioHMS.Application.Scheduling\SanatorioHMS.Application.Scheduling.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
