<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SanatorioHMS.Application.Core\SanatorioHMS.Application.Core.csproj" />
    <ProjectReference Include="..\..\Domain\SanatorioHMS.Domain.Scheduling\SanatorioHMS.Domain.Scheduling.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoWarn>$(NoWarn);CA1725</NoWarn>
  </PropertyGroup>

</Project>
